spring.application.name=BankingSystem


spring.datasource.url=jdbc:mysql://localhost:3306/banksystem
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=cyber
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=MySuperSecretKey12345678901234567890



logging.file.name=logs/banking-system.log
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

# application.properties
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
